package main

import (
	"fmt"

	_ "github.com/aws/aws-sdk-go"
	_ "github.com/brianvoe/gofakeit/v6"
	_ "github.com/dgrijalva/jwt-go"
	_ "github.com/disintegration/imaging"
	_ "github.com/elastic/go-elasticsearch"
	_ "github.com/gin-gonic/gin"
	_ "github.com/go-chi/chi"
	_ "github.com/go-playground/validator"
	_ "github.com/go-redis/redis"
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/golang-jwt/jwt/v5"
	_ "github.com/gonum/graph"
	_ "github.com/gorilla/mux"
	_ "github.com/gorilla/rpc"
	_ "github.com/gorilla/websocket"
	_ "github.com/hashicorp/consul/api"
	_ "github.com/icza/backscanner"
	_ "github.com/jackc/pgx/v5"
	_ "github.com/jmoiron/sqlx"
	_ "github.com/julienschmidt/httprouter"
	_ "github.com/lib/pq"
	_ "github.com/microcosm-cc/bluemonday"
	_ "github.com/miekg/dns"
	_ "github.com/nats-io/nats.go"
	_ "github.com/olekukonko/tablewriter"
	_ "github.com/olivere/elastic"
	_ "github.com/onsi/ginkgo/v2"
	_ "github.com/onsi/gomega"
	_ "github.com/panjf2000/ants/v2"
	_ "github.com/redis/go-redis/v9"
	_ "github.com/robfig/cron"
	_ "github.com/rs/zerolog"
	_ "github.com/segmentio/kafka-go"
	_ "github.com/sirupsen/logrus"
	_ "github.com/spf13/afero"
	_ "github.com/spf13/cobra"
	_ "github.com/spf13/pflag"
	_ "github.com/spf13/viper"
	_ "github.com/stretchr/testify"
	_ "github.com/twpayne/go-geom"
	_ "github.com/urfave/cli"
	_ "github.com/valyala/fasthttp"
	_ "github.com/valyala/fastjson"
	_ "go.uber.org/zap"
	_ "google.golang.org/grpc"
	_ "google.golang.org/protobuf"
)

func main() {
	fmt.Println("Hello, World!")
}
